<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13622" started-at="2018-08-22T08:26:08Z" finished-at="2018-08-22T08:26:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13622" started-at="2018-08-22T08:26:08Z" finished-at="2018-08-22T08:26:22Z">
      <class name="testing.TestScenario">
        <test-method status="FAIL" signature="testing(java.lang.String, java.lang.String)[pri:0, instance:testing.TestScenario@272113c4]" name="testing" duration-ms="13580" started-at="2018-08-22T01:26:08Z" data-provider="Dice Credentials" finished-at="2018-08-22T01:26:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sergius.la@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SuN-Qmw-S7k-Ybs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at testing.TestScenario.testing(TestScenario.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testing -->
        <test-method status="PASS" signature="endOfTest()[pri:0, instance:testing.TestScenario@272113c4]" name="endOfTest" is-config="true" duration-ms="1" started-at="2018-08-22T01:26:22Z" finished-at="2018-08-22T01:26:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endOfTest -->
      </class> <!-- testing.TestScenario -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
